name: Create Cypress report

on:
  workflow_dispatch:
  pull_request: 
    types: [opened]
jobs:
  
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses: actions/checkout@v2
      
#      - name: Install a project with a clean slate
#        run: |
#          npm ci
#          $(npm bin)/cypress cache path
#          $(npm bin)/cypress cache list
#          $(npm bin)/cypress verify
      
#      - name: Run Cypress tests
#        run: npm run test:chrome
#        continue-on-error: true
      
#      - name: Copy test execution videos
#        run: |
#          mkdir public
#          cp -r cypress/videos public/videos
      
#      - name: Merge test results into one
#        run: npm run report:merge
      
#      - name: Generate HTML report
#        run: npm run report:generate
      - name: Find Jira Issue
        uses: cybervoid/gajira-get-issue@v1.1
        id: find
        with:
          input-text: ${{ github.head_ref }}

      - name: Update PR body
        uses: AsasInnab/pr-body-action@v1
        if: steps.find.outputs.issue != ''
        id: body
        with:
          input-text: "[${{ steps.find.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.find.outputs.issue }})\n${{ github.event.pull_request.body }}"
          body: "[${{ steps.find.outputs.issue }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.find.outputs.issue }})\n${{ github.event.pull_request.body }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sction-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          # Field :컨텐트
          # repo : 창고 이름 및 링크
          # message : 메시지 및 링크 보내기
          # commit : 해싱 및 링크 제출
          # author : 병합된 사람
          # action : GiitHub Action에 링크된 결과
          # took : 작업 처리 시간
          # job : GiitHub Action의 작업 이름 및 링크
          # eventName : GiitHub Actions가 트리거한 이벤트 이름
          # ref : Giit의 참조
          # workflow : 워크플로우 이름 및 링크
          author_name: "${{ steps.body.outputs.issue }}"
          fields: repo,author,action,eventName,workflow,pullRequest # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
